security:
    
    encoders:
        Exia\CoreBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error|console)|css|images|js)/
            security: false
        #portfolio:
         #   pattern:   ^/portfolio
          #  anonymous: true
        main_login:
            pattern:   ^/connexion
            anonymous: true
        register:
            pattern:   ^/register
            anonymous: true

        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /
            remember_me:
                key:        %secret%    
                
    access_control:
        - { path: ^/(etablissements|etablissement|utilisateurs|utilisateur|professeurs|professeur), roles: ROLE_ADMIN }
